### ISSUE TITLE
cmap 3.1 format 4 problem fixed in FontLab 7.1

### ISSUE THREAD

**Issue by twardoch** [nomfoundation/font#1]
FontLab 7.1 exports the Windows-compatible OpenType `cmap` subtable 3.1 with format 4 more efficiently. This means that fonts with large glyph sets (>20,000 glyphs) now export correctly in more cases. The NomNaTongLight font now exports correctly out of the box. 

Because of the limitations of the OpenType format, there is no 100% guarantee that this will always work, but FontLab 7.1 makes better optimizations. To achieve additional optimization, do Font > Sort Glyphs > Unicode before exporting the font.

**Comment by nomfoundation** [comment]
Sorry for the belated comment, but many thanks for fixing this.
