### ISSUE TITLE
U+5580 喀 appears with an extra 宀 component very high above

### ISSUE THREAD

**Issue by guocuozuoduo** [nomfoundation/font#10]
Version 5.01
![image](https://user-images.githubusercontent.com/32423716/179342869-ffcf596d-5cfa-481a-b146-35ba6ec09a72.png)

**Comment by nomfoundation** [comment]
Thanks for reporting this. We will fix it in the next release.

**Comment by nomfoundation** [comment]
Fixed in 5.02, @guocuozuoduo, please verify and close

**Comment by eclairevoyant** [comment]
looks good to me personally
![image](https://user-images.githubusercontent.com/848000/187050717-506fbaee-9370-45a9-84bc-845e1139ab23.png)

**Comment by nomfoundation** [comment]
Please close it, thanks.
