### ISSUE TITLE
F1DAB should be mapped to 200C9

### ISSUE THREAD

**Issue by guocuozuoduo** [nomfoundation/font#12]
The character assigned to private use area F1DAB is identical to the Unicode character 200C9 𠃉，which is currently not included in the font.
[http://nomfoundation.org/common/nom_details.php?codepoint=f1dab](url)
![image](https://user-images.githubusercontent.com/32423716/182137463-991cc8bf-52b8-4a2e-8984-180009a839c4.png)
[http://yedict.com/zscontent.asp?uni=200C9](url)
![image](https://user-images.githubusercontent.com/32423716/182137769-4733b37a-3a2d-46e2-b85d-f4b01b7ec7d3.png)
(External Unicode character map showing the missing character)
![image](https://user-images.githubusercontent.com/32423716/182137528-211ec53e-c122-407a-8883-0e24ff2f3969.png)

**Comment by Hulenkius** [comment]
there are about ten glyphs in PUA that have their exact mapping in unicode standard. i ve calculated this months ago but not made a list, whose appearing would be fine.

**Comment by nomfoundation** [comment]
It would be helpful if you can provide a list.

Thanks.

**Comment by nomfoundation** [comment]
Fixed in 5.02, @guocuozuoduo  please verify and close
