### ISSUE TITLE
Stroke fault of ⿈

### ISSUE THREAD

**Issue by onichan0923** [nomfoundation/font#20]
康熙部首「⿈」的横笔存在问题。
另外，喃那宋的康熙部首/部首扩展区好像完全没有使用多重映射，为了节省字形数和统一风格，建议对和cjk表意文字区同形的康熙部首/部首扩展区字符使用多重映射。
There is a stroke fault in KangxiRadical ⿈.
Btw it is noticed that no multimapping is used in radicals. For concerns of glyph numbers and consistency, it is suggested to multimap some of the glyphs in KangxiRadical and CJKRadicalExt blocks with CJK ideographs.
![Screenshot_2023-04-08-12-57-47-43_c6d2f5838c1fca5283099d09ba458d93](https://user-images.githubusercontent.com/68043613/230704179-656361e1-40cc-4368-8397-dd1d6c4b99da.jpg)

**Comment by nomfoundation** [comment]
Verify with  v5.06

**Comment by onichan0923** [comment]
verified
