### ISSUE TITLE
Move the glyph of U+F0302 to U+3065C

### ISSUE THREAD

**Issue by KathrynCG** [nomfoundation/font#23]
![BAH@UG@JE9(BQ{`11E64$ C](https://user-images.githubusercontent.com/103583553/230728853-eda3ee4b-1624-4ff7-a745-45b8183e686a.png)
![U7@SOO~L8FJJSQCJY~2NS)I](https://user-images.githubusercontent.com/103583553/230728921-5d8a7ce8-b32f-45cf-92fb-8287249ec3c0.png)

**Comment by nomfoundation** [comment]
Verify with  v5.06
