### ISSUE TITLE
The glyph of U+F253A

### ISSUE THREAD

**Issue by KathrynCG** [nomfoundation/font#25]
![W) YE$8~A6Z~0F8JJ_RNTMJ](https://user-images.githubusercontent.com/103583553/235435397-1a0e9c05-5680-4e49-98ae-d418ca87a2f8.png)
Is it wrong?

**Comment by nomfoundation** [comment]
It appears that this is correct. I've pasted the page from Takeuchi below. I understand him to mean that this character is a combination of 似 and 那, with the left element 似 abbreviated to ⿰丶人, and mistakenly written 久, resulting in ⿰久那. Note that the current form of F253A appears twice.

![image](https://user-images.githubusercontent.com/58709218/236023906-015d4d5e-2f66-4113-ab83-4eb4c89f25b0.png)

**Comment by nomfoundation** [comment]
We can close this if you agree.
