### ISSUE TITLE
Support U+256F4 (𥛴)?

### ISSUE THREAD

**Issue by oong819** [nomfoundation/font#27]
For what i know U+256F4 are very close to the character "Tự" on Trần temple stamp (upper left character)

currently i cant find any font support this character

Can nomfoundation add U+256F4 to NomNaTong?

Sorry i know this are not an Nôm character

**Comment by nomfoundation** [comment]
U+256F4 is a variant of 禩 U+79A9, which is in the NomNaTong font.

Can you provide an image of the stamp?

Thanks,

**Comment by oong819** [comment]
an image i found online: https://hinhanhvietnam.com/wp-content/uploads/2016/02/an-den-nha-tran.jpg

based on the image i think its an old variant of 祀 instead of U+256F4 which was already supported. sorry for this, closing

and Unicode seems to not yet support ⿰示巳
