### ISSUE TITLE
Contributions for the font and Nôm dictionary

### ISSUE THREAD

**Issue by Liu2k5** [nomfoundation/font#28]
Hi, I'm just an enthusiastic of Nôm script. I have read a bit of Nôm books. I've found some characters not existing in the font and the dictionary. I use the web zi.tools as well to look up characters. There might be some characters not updated yet and because I'm not able to check if one has been in the font or not (sorry for my limited skill), so I will list ones that I presume they need to be added.
*Note : These pages are from book "Ngọc Hoàng phổ độ Tôn kinh Quốc âm". Besides, the meanings are just my thought, I just tried to translated the sentences to quốc ngữ on myself so they might be wrong.
![nlvnpf-0305-004](https://github.com/nomfoundation/font/assets/118142971/7f2a73db-07cf-43f7-b288-1aa0a4236d3b)

**Comment by Liu2k5** [comment]
![image](https://github.com/nomfoundation/font/assets/118142971/e975eabe-bab9-41a5-a8c4-74b820c2c533)
This character is read "chảy" (flow), according to the pronunciation of Kinh people in China.

**Comment by Liu2k5** [comment]
![nlvnpf-0305-004](https://github.com/nomfoundation/font/assets/118142971/c4c54dfc-38bf-4338-b604-04b37a2b7aff)
.

**Comment by nomfoundation** [comment]
Already supported:
U+8B72	譲	nhường nhàng
U+2404B	𤁋	lách rạch, standard form is 瀝
VN-F2038	󲀸	⿰氵走	tsai3 = chảy

To be added:
⿱山忽	UK-20073 in IRG WS2021

These are composed with U+16FF1, nháy. We can add glyphs to the font to improve the appearance:
招𖿱
算𖿱

**Comment by Liu2k5** [comment]
![nlvnpf-0305-006](https://github.com/nomfoundation/font/assets/118142971/b345150a-1798-460b-b2f6-1c6ff73de9f9)
![nlvnpf-0305-008](https://github.com/nomfoundation/font/assets/118142971/305bf2df-9b70-40f7-b135-7f481b6cf36e)
![nlvnpf-0305-007](https://github.com/nomfoundation/font/assets/118142971/d697ccc9-4fd5-44e9-a658-4b000dc64e11)

**Comment by nomfoundation** [comment]
Added in v5.10, please verify and close.

**Comment by Liu2k5** [comment]
![image](https://github.com/nomfoundation/font/assets/118142971/631d87a1-23f1-4001-b014-a8ee32564529)
I assume it has the form ⿰卒通

![nlvnpf-0305-009](https://github.com/nomfoundation/font/assets/118142971/a460867e-9bf0-49dc-ad77-958fbf4f4684)
![nlvnpf-0305-010](https://github.com/nomfoundation/font/assets/118142971/b52622d5-687a-4958-b02f-3e068cdc76cd)
![nlvnpf-0305-011](https://github.com/nomfoundation/font/assets/118142971/03b37415-6987-4c59-9de8-f81a99cf2706)
![nlvnpf-0305-012](https://github.com/nomfoundation/font/assets/118142971/15867fbb-b067-40cb-a6d0-16f23aec50cf)

**Comment by nomfoundation** [comment]
If v5.10 correctly addresses issue #28, please close that issue and create a new issue for any additional characters.
