### ISSUE TITLE
Additional characters in the book Ngọc Hoàng phổ độ tôn kinh

### ISSUE THREAD

**Issue by Liu2k5** [nomfoundation/font#29]
![image](https://github.com/nomfoundation/font/assets/118142971/631d87a1-23f1-4001-b014-a8ee32564529)
I assume it has the form ⿰卒通

![nlvnpf-0305-009](https://github.com/nomfoundation/font/assets/118142971/a460867e-9bf0-49dc-ad77-958fbf4f4684)
![nlvnpf-0305-010](https://github.com/nomfoundation/font/assets/118142971/b52622d5-687a-4958-b02f-3e068cdc76cd)
![nlvnpf-0305-011](https://github.com/nomfoundation/font/assets/118142971/03b37415-6987-4c59-9de8-f81a99cf2706)
![nlvnpf-0305-012](https://github.com/nomfoundation/font/assets/118142971/15867fbb-b067-40cb-a6d0-16f23aec50cf)

**Comment by nomfoundation** [comment]
The full form of ⿰𱑎通 is probably ⿰率通, which is a variant of U+28656 𨙖 (suốt). See Tự điển chữ nôm trích dẫn for information about this component:
![image](https://github.com/nomfoundation/font/assets/58709218/c4a37a66-b779-4509-a3f3-29846e54c8bb)

**Comment by Liu2k5** [comment]
![nlvnpf-0305-015](https://github.com/nomfoundation/font/assets/118142971/86740e37-c8de-45dd-91d5-a494e29dab1a)
![nlvnpf-0305-013](https://github.com/nomfoundation/font/assets/118142971/e99fe0fb-f671-4635-94ff-04b761a073c3)

**Comment by nomfoundation** [comment]
Working on this. Note, according to TĐCNTD, ⿱共血 is a variant of 蓋
![image](https://github.com/nomfoundation/font/assets/58709218/c370aa29-9ee8-4569-86f7-ffbfd536d922)

Would like to confirm that "yên", has nháy: 
![image](https://github.com/nomfoundation/font/assets/58709218/b5a0501a-0748-4455-9502-5dd112bccf8b)

**Comment by nomfoundation** [comment]
Please

**Comment by nomfoundation** [comment]
Please verify and close.
