### ISSUE TITLE
Glyph artefacts for more characters

### ISSUE THREAD

**Issue by tonton-pixel** [nomfoundation/font#3]
Following the opening of issue #2, I wish to report other glyph "artefacts" in the current `NomNaTong V4.8` font, that were spotted in a more systematic way. Some appear to concern components which are common to several characters, it might be wise to check other ones as well...

```
U+2150D 𡔍
U+2A977 𪥷
```

![U+2150D](https://user-images.githubusercontent.com/26766930/156664168-6b78bdc0-ec28-45ca-a719-62dc16eeb2d9.png)
![U+2A977](https://user-images.githubusercontent.com/26766930/156663957-7acd9e05-ec4f-489b-abee-16c670b5af69.png)

```
U+81C1  臁
U+21E85 𡺅
```

![U+81C1](https://user-images.githubusercontent.com/26766930/156664384-7093c137-aef0-4186-b1dd-d59074cf5eb5.png)
![U+21E85](https://user-images.githubusercontent.com/26766930/156664479-f7d2d54f-c09b-4331-bf61-04264a5848dc.png)

```
U+5A41  婁
U+5C62  屢
U+5DFD  巽
U+5F3C  弼
U+6A81  檁
U+6B17  欗
U+7C63  籣
U+7C97  粗
U+7CA5  粥
U+7DCD  緍
U+7FE1  翡
U+8A5B  詛
U+8B8E  讎
U+8CBB  費
U+9AF4  髴
U+50D1  僑
U+50ED  僭
U+53CC  双
U+56D2  囒
U+59D0  姐
U+62AF  抯
U+64BE  撾
U+82F3  苳
U+89C0  觀
U+95AD  閭
U+558E  喎
U+711D  焝
U+798D  禍
U+857D  蕽
U+862D  蘭
U+915F  酟
U+971E  霞
U+5480  咀
U+5640  噀
U+5686  嚆
U+7061  灡
U+7532  甲
U+7570  異
U+8300  茀
U+8463  董
U+8517  蔗
U+9700  需
U+9803  頃
U+9805  項
U+9808  須
U+3619  㘙
U+372E  㜮
U+2A7E6 𪟦
U+2AC58 𪱘
U+2AFC4 𪿄
U+2B115 𫄕
U+2B44C 𫑌
U+2B451 𫑑
U+2BB54 𫭔
U+2BCB4 𫲴
U+2BE0C 𫸌
U+2BF96 𫾖
U+2C091 𬂑
U+2C139 𬄹
U+2C512 𬔒
U+2C6B6 𬚶
U+2C682 𬚂
U+2C749 𬝉
U+2CA16 𬨖
U+2CA5F 𬩟
U+2CA55 𬩕
U+2CA67 𬩧
U+2CD7F 𬵿
U+2CE34 𬸴
U+20016 𠀖
U+20017 𠀗
U+20AC6 𠫆
U+20BCB 𠯋
U+20C93 𠲓
U+20C96 𠲖
U+20EC3 𠻃
U+20F37 𠼷
U+20FBC 𠾼
U+21031 𡀱
U+2105C 𡁜
U+2114C 𡅌
U+21149 𡅉
U+21196 𡆖
U+21514 𡔔
U+21BA3 𡮣
U+2202D 𢀭
U+2218D 𢆍
U+228C4 𢣄
U+22963 𢥣
U+22982 𢦂
U+22D0C 𢴌
U+22D3E 𢴾
U+22DC6 𢷆
U+22EA4 𢺤
U+232F0 𣋰
```

![U+5A41](https://user-images.githubusercontent.com/26766930/156664789-f707335c-59e0-4b58-ae94-bbc67c743693.png)
![U+5C62](https://user-images.githubusercontent.com/26766930/156664792-1566a519-a9ac-4f1a-afee-1989840f6123.png)
![U+5DFD](https://user-images.githubusercontent.com/26766930/156664793-9f9d5fa5-de9a-4e03-9514-1d7ba05b0845.png)
![U+5F3C](https://user-images.githubusercontent.com/26766930/156664796-06db328f-9fed-4e4b-b51e-93b972ac129e.png)
![U+6A81](https://user-images.githubusercontent.com/26766930/156664798-bfd8b819-06d7-4da3-b1b1-705cac2de282.png)
![U+6B17](https://user-images.githubusercontent.com/26766930/156664801-54cfee52-76b6-4d4b-9a17-15e5fe7336e4.png)
![U+7C63](https://user-images.githubusercontent.com/26766930/156664923-f7eea8cf-9ed1-4891-b805-1619dcd83176.png)
![U+7C97](https://user-images.githubusercontent.com/26766930/156664928-a0e28997-2fa9-4f64-b69a-81e867193227.png)
![U+7CA5](https://user-images.githubusercontent.com/26766930/156664930-54079fd2-0ee2-4650-824e-25f9f16ec955.png)
![U+7DCD](https://user-images.githubusercontent.com/26766930/156664932-9f345560-9328-449d-b043-955db3158f7c.png)
![U+7FE1](https://user-images.githubusercontent.com/26766930/156664934-1c37e281-a22d-4ea6-905b-a882af7f484c.png)
![U+8A5B](https://user-images.githubusercontent.com/26766930/156664937-2cfe30cf-a551-49a2-a88c-13fda096abc7.png)
![U+8B8E](https://user-images.githubusercontent.com/26766930/156664940-34f73168-8d1c-42dd-a9a9-6ecb610b5122.png)
![U+8CBB](https://user-images.githubusercontent.com/26766930/156664942-5c7b86b5-1f60-4556-a689-6d86d5d72c9b.png)
![U+9AF4](https://user-images.githubusercontent.com/26766930/156664946-6dd8c6e6-ef0d-44c8-8157-7626defe604b.png)
![U+50D1](https://user-images.githubusercontent.com/26766930/156664950-af328ba8-0ed7-4ee1-9f4a-37b0f4faacab.png)
![U+50ED](https://user-images.githubusercontent.com/26766930/156664957-71a1f122-662e-47cb-86db-13dd3d1c0329.png)
![U+53CC](https://user-images.githubusercontent.com/26766930/156664962-55f92fad-890e-4782-be13-65ecedceb7de.png)
![U+56D2](https://user-images.githubusercontent.com/26766930/156664968-596db846-2da9-4748-96f2-d672ac3e95db.png)
![U+59D0](https://user-images.githubusercontent.com/26766930/156664975-66cdbf79-1051-4d1c-a4d0-5007b18f4da1.png)
![U+62AF](https://user-images.githubusercontent.com/26766930/156664977-19811563-2d0c-46cf-aac7-d375d7255cfd.png)
![U+64BE](https://user-images.githubusercontent.com/26766930/156664980-71698b16-9092-4a22-be1d-36c9aa512ab5.png)
![U+82F3](https://user-images.githubusercontent.com/26766930/156664981-93454995-6d5e-42d9-8f9e-4d75b1b0d19d.png)
![U+89C0](https://user-images.githubusercontent.com/26766930/156664983-565765e9-a20e-4777-a241-843c0c17078c.png)
![U+95AD](https://user-images.githubusercontent.com/26766930/156664985-6ec7fc40-996e-426b-a275-248498aa9041.png)
![U+558E](https://user-images.githubusercontent.com/26766930/156664986-74f3030b-d54d-4dd1-b588-f610b1baf416.png)
![U+711D](https://user-images.githubusercontent.com/26766930/156664989-2854297f-e7f3-40bc-adc6-3cc2eeb7aea8.png)
![U+798D](https://user-images.githubusercontent.com/26766930/156664991-e84e4ee9-80d6-4ef0-a93f-4745955f9820.png)
![U+857D](https://user-images.githubusercontent.com/26766930/156664993-7af3b890-ab32-4910-be0c-787767753631.png)
![U+862D](https://user-images.githubusercontent.com/26766930/156664998-26f0b6db-9c0d-4770-80a3-46571a9cc111.png)
![U+915F](https://user-images.githubusercontent.com/26766930/156664999-cee766b9-dd2a-40a5-acf3-f69c57fc4abd.png)
![U+971E](https://user-images.githubusercontent.com/26766930/156665002-28f875b8-4bf5-46e3-8f48-39a82b385fed.png)
![U+5480](https://user-images.githubusercontent.com/26766930/156665004-1b7a3397-7c3c-4293-8502-e007338a0e15.png)
![U+5640](https://user-images.githubusercontent.com/26766930/156665006-7d8a7ea7-fc2c-42b7-923c-e6bf1c4f936c.png)
![U+5686](https://user-images.githubusercontent.com/26766930/156665012-060ab400-1fe6-4958-b6a2-1548b1975366.png)
![U+7061](https://user-images.githubusercontent.com/26766930/156665016-0f5f7ec7-a889-49ac-ad9f-0681f60082f6.png)
![U+7532](https://user-images.githubusercontent.com/26766930/156665017-26d9cf1d-512c-48c6-b028-1dd990cab2c3.png)
![U+7570](https://user-images.githubusercontent.com/26766930/156665020-95efbb54-c691-4a36-afed-280f958e8cb2.png)
![U+8300](https://user-images.githubusercontent.com/26766930/156665023-1287715e-6315-48e7-8daf-a6f1323231bb.png)
![U+8463](https://user-images.githubusercontent.com/26766930/156665025-42d09b0a-234b-445c-af6d-09949bfe44dc.png)
![U+8517](https://user-images.githubusercontent.com/26766930/156665028-96eb4809-d65a-44f7-bfed-a798af2a4690.png)
![U+9700](https://user-images.githubusercontent.com/26766930/156665032-a79de67d-5c59-4e0d-8fac-31a0e96cbca2.png)
![U+9803](https://user-images.githubusercontent.com/26766930/156665035-03329429-6d08-4ca0-999e-87f87f69fdf4.png)
![U+9805](https://user-images.githubusercontent.com/26766930/156665038-e696fc2e-bf53-4484-86fd-1efabee4b4a8.png)
![U+9808](https://user-images.githubusercontent.com/26766930/156665042-4bf4bb3e-49cc-4aa5-a5c3-aae97cdd2193.png)
![U+3619](https://user-images.githubusercontent.com/26766930/156665048-0039c920-d638-4342-b989-d59cb09026b9.png)
![U+372E](https://user-images.githubusercontent.com/26766930/156665055-1f863213-3cd1-454f-b1cf-43fa2b6bda8b.png)
![U+2A7E6](https://user-images.githubusercontent.com/26766930/156665060-ae683d51-42dd-4c0f-8ce9-c52008f765a4.png)
![U+2AC58](https://user-images.githubusercontent.com/26766930/156665064-ea7a936e-fd2d-4ce1-93eb-ce157ee241dc.png)
![U+2AFC4](https://user-images.githubusercontent.com/26766930/156665068-ab4c2d56-37aa-4f37-a545-d164cdee2d46.png)
![U+2B115](https://user-images.githubusercontent.com/26766930/156665074-f4098549-a9b6-45b5-9a0a-e5db04423c75.png)
![U+2B44C](https://user-images.githubusercontent.com/26766930/156665079-ac855f8e-d427-441a-95ca-da63c320fbbd.png)
![U+2B451](https://user-images.githubusercontent.com/26766930/156665086-3c2f5ce2-fe0f-47b6-8f34-6d0b10a45a95.png)
![U+2BB54](https://user-images.githubusercontent.com/26766930/156665088-76d23d58-4f59-4977-a3e9-c8df124749b9.png)
![U+2BCB4](https://user-images.githubusercontent.com/26766930/156665089-f0afe9d6-0daf-4a8c-94ce-3c77b111fc1e.png)
![U+2BE0C](https://user-images.githubusercontent.com/26766930/156665090-4d823151-f9e8-4ffd-b451-c88beb990cca.png)
![U+2BF96](https://user-images.githubusercontent.com/26766930/156665091-28f3d810-1c73-4ccb-8145-cf25ccf993f7.png)
![U+2C091](https://user-images.githubusercontent.com/26766930/156665095-d787e115-58ce-4bbd-9ae0-7c10eb415ffe.png)
![U+2C139](https://user-images.githubusercontent.com/26766930/156665098-4b4dd6ce-a171-4647-a054-e020c376b248.png)
![U+2C512](https://user-images.githubusercontent.com/26766930/156665099-efdf3568-48f2-4cd5-8aac-b0559143e3f8.png)
![U+2C6B6](https://user-images.githubusercontent.com/26766930/156665103-412bacd2-9c4a-4454-8b07-2300f129b95d.png)
![U+2C682](https://user-images.githubusercontent.com/26766930/156665107-a769ddc3-6dae-4f70-a478-d77b6bdbe738.png)
![U+2C749](https://user-images.githubusercontent.com/26766930/156665108-f7014aa9-10c9-4524-8ad6-5062c97316a7.png)
![U+2CA16](https://user-images.githubusercontent.com/26766930/156665111-c5b4b032-aeb1-4155-b86a-048551f9afaf.png)
![U+2CA5F](https://user-images.githubusercontent.com/26766930/156665113-da30e169-9460-40f4-91ea-88879a181cfd.png)
![U+2CA55](https://user-images.githubusercontent.com/26766930/156665116-e01d85d4-d77d-42ec-a596-aaa3c7cdb9bc.png)
![U+2CA67](https://user-images.githubusercontent.com/26766930/156665120-33e10fc8-c6e3-4a71-b64c-8ad7bc48a1d9.png)
![U+2CD7F](https://user-images.githubusercontent.com/26766930/156665122-54f46a14-1130-4e34-9ad5-93a21788b450.png)
![U+2CE34](https://user-images.githubusercontent.com/26766930/156665124-4ef70e1b-a304-4dfa-9105-0056580bcd07.png)
![U+20016](https://user-images.githubusercontent.com/26766930/156665127-18fa6a21-4af0-4f27-a8e9-d7a96bad9983.png)
![U+20017](https://user-images.githubusercontent.com/26766930/156665131-0f874009-a7fa-4046-8a2c-d46c8ea89e77.png)
![U+20AC6](https://user-images.githubusercontent.com/26766930/156665134-a942e469-aa2f-47b4-afdb-4c06081ce4aa.png)
![U+20BCB](https://user-images.githubusercontent.com/26766930/156665135-68612554-a2ba-48db-a90d-15ae02e9300f.png)
![U+20C93](https://user-images.githubusercontent.com/26766930/156665139-805b27b3-2628-4793-8c99-76ed67dc149c.png)
![U+20C96](https://user-images.githubusercontent.com/26766930/156665144-d66ae202-2f3e-41ab-9dec-c0f5a529ba59.png)
![U+20EC3](https://user-images.githubusercontent.com/26766930/156665148-8d0d8a77-6813-433c-8513-bf5a0ee45765.png)
![U+20F37](https://user-images.githubusercontent.com/26766930/156665149-293bb4dc-08b0-4885-bf23-65fcb77152ea.png)
![U+20FBC](https://user-images.githubusercontent.com/26766930/156665150-e568e46e-041f-4df7-8958-404bea4609aa.png)
![U+21031](https://user-images.githubusercontent.com/26766930/156665152-951ce507-4432-496a-b9ae-57f22a9eb9a3.png)
![U+2105C](https://user-images.githubusercontent.com/26766930/156665157-3cdd524d-6b69-40d7-b11b-167c2aa7ec2e.png)
![U+2114C](https://user-images.githubusercontent.com/26766930/156665158-71b13bf6-b7a4-47fb-9452-b1fbca3178a5.png)
![U+21149](https://user-images.githubusercontent.com/26766930/156665160-a62c5afe-1f64-45c3-a799-3621bde13124.png)
![U+21196](https://user-images.githubusercontent.com/26766930/156665162-b11ffe9b-2f00-4b56-826c-d3463e865d32.png)
![U+21514](https://user-images.githubusercontent.com/26766930/156665164-ba27e954-0cbb-4ebc-911c-f6c583e223ea.png)
![U+21BA3](https://user-images.githubusercontent.com/26766930/156665168-4043d344-0cf0-4a61-b443-f4cdc5747a25.png)
![U+2202D](https://user-images.githubusercontent.com/26766930/156665171-3e1cda41-6c2e-4f47-b754-abcb8efef6d9.png)
![U+2218D](https://user-images.githubusercontent.com/26766930/156665176-0b91f31c-9d82-433a-a5db-3149401c674f.png)
![U+228C4](https://user-images.githubusercontent.com/26766930/156665177-5e56c822-a52f-4a4d-b6a6-4382ffe20623.png)
![U+22963](https://user-images.githubusercontent.com/26766930/156665180-8afce7d7-25bd-4f98-a28c-773219c70229.png)
![U+22982](https://user-images.githubusercontent.com/26766930/156665183-5383e02b-9a90-4d93-a121-4b6766da744a.png)
![U+22D0C](https://user-images.githubusercontent.com/26766930/156665188-d0e133a0-e571-4372-9b42-91b30f30bc98.png)
![U+22D3E](https://user-images.githubusercontent.com/26766930/156665191-62fecc48-4bee-4e84-af02-40133f91fb58.png)
![U+22DC6](https://user-images.githubusercontent.com/26766930/156665192-31d3c174-a945-425a-b2a1-cb9cdadc834f.png)
![U+22EA4](https://user-images.githubusercontent.com/26766930/156665193-00ea2392-b687-48e3-96d1-3076c7108dcb.png)
![U+232F0](https://user-images.githubusercontent.com/26766930/156665197-d1b4e679-6ab3-49b0-93be-52312823d673.png)

**Comment by nomfoundation** [comment]
Fixed in 5.0 @tonton-pixel please, verify and close
