### ISSUE TITLE
Add support for this character "lợi" in Phật thuyết đại báo phụ mẫu ân trọng kinh

### ISSUE THREAD

**Issue by HyKNH** [nomfoundation/font#33]
![Screenshot 2024-10-02 215816](https://github.com/user-attachments/assets/a42c0a92-086b-40ee-8a32-9b2dd555efba)
![Screenshot 2024-10-02 215948](https://github.com/user-attachments/assets/a1d77ae8-a8a8-4cd8-8a0a-d03dcba59844)

(⿱⿰巜巜⿰刂禾)

存亡俱[⿱⿰巜巜⿰刂禾]樂 
Tồn vong cụ lợi lạc

群折調共利樂 
Còn chết đều cùng lợi lạc

**Comment by nomfoundation** [comment]
The latest version of the font has two variants of this character in the PUA: U+F0738 and U+F2614. One question we have about the glyph shown in the “Phật thuyết” is that the top appears to be ⿰从从, not ⿰巜巜. Also, the 刂 element does not have a hook at the bottom of the second stroke. We would be very interested to learn more about this glyph, and whether or not there are examples found in other texts
