### ISSUE TITLE
Suspicious lost stroke for U+24F15 𤼕

### ISSUE THREAD

**Issue by Hulenkius** [nomfoundation/font#34]
![image](https://github.com/user-attachments/assets/2dcd0a10-ef41-4365-8312-e9dd39499eb7)
![image](https://github.com/user-attachments/assets/7a262c47-1fd6-492b-963f-0e72d0d13cfe)
![772804aa67bb2ee7dcc0c33b756ce558](https://github.com/user-attachments/assets/fee1adc9-9ee8-46e0-be97-eff898f95cc1)

**Comment by kenlunde** [comment]
@nomfoundation When submitted a document with the updated glyph, also be sure to included updated _kRSUnicode_ and _kTotalStrokes_ property values if 音 and 戈 are not connected via the common horizontal stroke:

```
U+24F15 kRSUnicode 104.18 → 104.19
U+24F15 kTotalStrokes 23 → 24
```

**Comment by nomfoundation** [comment]
We plan to join the stroke between 音 and 戈, so the stroke count will remain the same.

**Comment by nomfoundation** [comment]
Please verify with release v5.13

**Comment by Hulenkius** [comment]
Solved.
