### ISSUE TITLE
Nom Na Tong version 4.9

### ISSUE THREAD

**Issue by tonton-pixel** [nomfoundation/font#5]
Many thanks for this new version.

I took the liberty to visually check all the changes of issues I reported earlier, everything is just fine; however, I found two possible minor issues:

- There is still an almost unnoticeable tiny glitch in the outline of the glyph for `U+23E5E 𣹞`. Please see the enlarged detail:

<img width="152" alt="U+23E5E-detail" src="https://user-images.githubusercontent.com/26766930/157212960-249ec2ff-13f8-488d-8231-a680d5a2953b.png">

- The corrected glyph of `U+95AD 閭` is now `⿵門吕`; it used to be `⿵門呂` in version 4.8; this may be intentional, or not...

![U+95AD-new](https://user-images.githubusercontent.com/26766930/157214060-e2c6eb6d-5701-41c5-9e8b-a38af20b7291.png)

**Comment by nomfoundation** [comment]
Michel,

Thanks for reporting these.

The first issue in  U+23E5E is in the earliest version of the font we have, 2.8, so it's not a recent regression. It needs to be fixed, though.

The second issue with U+95AD is a regression from 4.8.

We will fix both problems in the next release of the master font 4.9+, and in the 4.6x version of the font used for Unicode, which should be soon.

Lee

**Comment by nomfoundation** [comment]
These issues were addressed in 5.0. @tonton-pixel, please verify and close.
