### ISSUE TITLE
Missing Unicode characters cause bugged display on nomfoundation site

### ISSUE THREAD

**Issue by guocuozuoduo** [nomfoundation/font#9]
The font is missing several characters that are already in Unicode, which causes display problems in the Nôm Lookup Tool on the nomfoundation site (the missing characters appear in the system's default font or just as a square). So far, these characters were found:
- 58fa 壺 hồ
![image](https://user-images.githubusercontent.com/32423716/178722827-77b7b247-702f-43d0-ba9e-a8d958908fe1.png)
- 2d4c7 𭓇 học
![image](https://user-images.githubusercontent.com/32423716/178722879-617778fe-0f04-40bc-918f-c302db6a3bde.png)
- 31020 𱀠 quy
![image](https://user-images.githubusercontent.com/32423716/178722941-86b29346-343c-4117-a86e-46d0bd8bac50.png)
As these characters are all variants of other characters, it is likely there are more variant characters that have been included in Nôm Lookup Tool but missing in the font. I will follow up as I find more of them.

**Comment by nomfoundation** [comment]
As you can see below, the  glyphs in question are all supported, and have been at least back to V 4.3 of NomNaTong, if not earlier.

The font in the images provided by guocuozuoduo seems somewhat lighter thatn NomNaTong-Regular.  Can you tell us which platform and browser you are using?

One problem might be the browser. I know that Safari, on the Mac, no longer supports custom fonts. I suggest Chrome or Firefox if you use Mac. I don't know about the situation on Windows.


Best

Lee

**Comment by guocuozuoduo** [comment]
Thanks for the reply.

It appears that my installation of NomNaTong-Regular.**otf** v5.01 did not overlap the NomNaTong-Light.**ttf** v4.3 already in the system. I have deleted the old ttf and reinstalled the new otf, and the characters appear normal again.
(For reference, I am using Windows 10 and Microsoft Edge 104.0.1279.0 canary 64bit.)

Apologies for any inconvenience this has caused.

Regards,
guocuozuoduo
